language: python

python:
  - 2.7

install:
  - "pip install -r sonny/deploy/requirements.txt"

script:
  - "./run-tests.sh"

services:
  - mysql
  - postgresql

 before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c 'create database test;' -U postgres

