language: python

python:
  - 2.7

install:
  - "pip install -r tangent_importer/deploy/requirements.txt"

script:
  - "./run-tests.sh"

services:
  - mysql

 before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

